- name: Check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: Download Rust Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: Install Rust
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y

# TODO: DRY this block
- name: Check if {{ ansible_env.HOME }}/.bashrc exists
  stat:
    path: "{{ ansible_env.HOME }}/.bashrc"
  register: bashrc_exists

- name: Ensure cargo environment is sourced from the .bashrc
  when: bashrc_exists.stat.exists
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      [ -f ~/.cargo/env ] && source $HOME/.cargo/env
    marker: '# {mark} ANSIBLE MANAGED BLOCK - Rust Cargo'
    insertbefore: BOF
    create: yes

- name: Check if {{ ansible_env.HOME }}/.zshrc exists
  stat:
    path: "{{ ansible_env.HOME }}/.zshrc"
  register: zshrc_exists

- name: Ensure cargo environment is sourced from the .zshrc
  when: zshrc_exists.stat.exists
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    block: |
      [ -f ~/.cargo/env ] && source $HOME/.cargo/env
    marker: '# {mark} ANSIBLE MANAGED BLOCK - Rust Cargo'
    insertbefore: BOF
    create: yes
# END TODO: DRY this block

# Used in some `many-rs` tests
- name: Install "cbor-diag-cli" Rust package
  community.general.cargo:
    name: cbor-diag-cli
    version: "0.1.8"
